# Generated by Django 5.0.3 on 2024-03-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='react',
            name='color',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='react',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='react',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='react',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='make',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='model',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
