# Generated by Django 5.0.3 on 2024-03-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_react_detail_remove_react_name_react_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='age',
        ),
        migrations.RemoveField(
            model_name='react',
            name='color',
        ),
        migrations.RemoveField(
            model_name='react',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='react',
            name='email',
        ),
        migrations.RemoveField(
            model_name='react',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='react',
            name='id_num',
        ),
        migrations.RemoveField(
            model_name='react',
            name='make',
        ),
        migrations.RemoveField(
            model_name='react',
            name='model',
        ),
        migrations.RemoveField(
            model_name='react',
            name='password',
        ),
        migrations.AlterField(
            model_name='react',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='react',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
