# Generated by Django 5.0.3 on 2024-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_react_age_remove_react_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
