# Generated by Django 5.0.3 on 2024-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_react_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
