# Generated by Django 5.0.3 on 2024-03-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_react_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
