# Generated by Django 5.0.3 on 2024-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_react_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
