# Generated by Django 5.0.3 on 2024-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_react_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='id_num',
            field=models.IntegerField(default=0),
        ),
    ]
