# Generated by Django 5.0.3 on 2024-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_react_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='color',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='make',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='model',
            field=models.CharField(default='', max_length=30),
        ),
    ]
